#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Matrix >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Matrix=/luci-static/matrix
		set luci.main.mediaurlbase=/luci-static/matrix
		commit luci
	EOF
fi

exit 0
